### ISSUE TITLE
Research uses for user activity

### ISSUE THREAD

**Issue by jerrettl** [SWIM-ucf/Design-Document#20]
Imported from Google Doc:

> Muscises - Need to figure out more uses for user activity for SWIM

https://github.com/SWIM-ucf/Design-Document/blob/2a9efe1dd1fea27ff9afd971b80d27de67a077d0/swim.tex#L4380-L4385

**Comment by ehraiford** [comment]
Since we aren't storing user activity at all so this wordage needs to change.

**Comment by b0x-Cub3d** [comment]
Since I removed the Storing Session Data section, this is no longer applicable.
