### ISSUE TITLE
Test offline use

### ISSUE THREAD

**Issue by jerrettl** [SWIM-ucf/Design-Document#21]
Imported from Google Doc:

> Muscises - DEFINITELY WANT TO TEST THIS!!! :)

https://github.com/SWIM-ucf/Design-Document/blob/2a9efe1dd1fea27ff9afd971b80d27de67a077d0/swim.tex#L4505-L4508

**Comment by ehraiford** [comment]
This has been tested and works. Wordage needs to be updated.
