### ISSUE TITLE
Add further Rust and WebAssembly compilation steps

### ISSUE THREAD

**Issue by jerrettl** [SWIM-ucf/Design-Document#6]
Imported from Google Doc:

> Muscises - [https://rustwasm.github.io/docs/book/game-of-life/introduction.html](https://www.google.com/url?q=https://rustwasm.github.io/docs/book/game-of-life/introduction.html&sa=D&source=docs&ust=1671484427105440&usg=AOvVaw0npnFaw7S44cswKMOo3ZW9)
>
> There's more specified steps to the process, so I'll add them in the future.

https://github.com/SWIM-ucf/Design-Document/blob/2a9efe1dd1fea27ff9afd971b80d27de67a077d0/swim.tex#L1532-L1553

**Comment by jerrettl** [comment]
https://github.com/SWIM-ucf/Design-Document/blob/2a9efe1dd1fea27ff9afd971b80d27de67a077d0/swim.tex#L1532-L1553

**Comment by b0x-Cub3d** [comment]
I'm going to close this since I now see this as a means of what you had to do to build Wasm apps back then vs. now.
