### ISSUE TITLE
Write more on Yew section

### ISSUE THREAD

**Issue by jerrettl** [SWIM-ucf/Design-Document#7]
Imported from Google Doc:

> Muscises - Still have more to fill out.

https://github.com/SWIM-ucf/Design-Document/blob/2a9efe1dd1fea27ff9afd971b80d27de67a077d0/swim.tex#L1607-L1609

**Comment by jerrettl** [comment]
Imported from Google Doc:

> Still have more to fill out.

https://github.com/SWIM-ucf/Design-Document/blob/2a9efe1dd1fea27ff9afd971b80d27de67a077d0/swim.tex#L1607-L1609

**Comment by ehraiford** [comment]
At the very least,  double check the section that it is still valid with 0.20 and remove the caveat saying it might not be at the beginning.
