### ISSUE TITLE
Explain virtual DOM and `ref`

### ISSUE THREAD

**Issue by jerrettl** [SWIM-ucf/Design-Document#9]
Imported from Google Doc:

> Yew uses a virtual DOM? "Virtual DOM" has not yet been mentioned in this section and was unclear to me.
>
> "ref" sounds cool, but what is it? A function, a module, a crate, etc. I'm not sure of the context of how this would be used in implementation.
>
> Restating what exactly? I don't remember seeing anything about implementing "component" up to this point.

https://github.com/SWIM-ucf/Design-Document/blob/2a9efe1dd1fea27ff9afd971b80d27de67a077d0/swim.tex#L1723-L1736

**Comment by jerrettl** [comment]
Imported from Google Drive:

> Yew uses a virtual DOM? "Virtual DOM" has not yet been mentioned in this section and was unclear to me.
>
> "ref" sounds cool, but what is it? A function, a module, a crate, etc. I'm not sure of the context of how this would be used in implementation.
>
> Restating what exactly? I don't remember seeing anything about implementing "component" up to this point.

https://github.com/SWIM-ucf/Design-Document/blob/2a9efe1dd1fea27ff9afd971b80d27de67a077d0/swim.tex#L1723-L1736

**Comment by ehraiford** [comment]
We probably won't have time for this. If we don't, we just need to make sure that we delete the comment.

**Comment by jerrettl** [comment]
Marked as `wontfix`. `ref` wasn't used almost at all in this project. Remember to remove comment.

**Comment by b0x-Cub3d** [comment]
I added in the nature of the virtual DOM and how it works here: https://github.com/SWIM-ucf/Design-Document/blob/main/swim.tex#L1688
